/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.swing;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import vistas.general.VentanaGeneral;
/**
 *
 * @author prometheus
 */
public class VentanaReportes extends VentanaGeneral {

    /**
     * Creates new form
     * @param accion
     */
    public VentanaReportes(ActionListener accion, MouseListener ml) {
        initComponents();
        setLocationRelativeTo(null);
        this.agregarListener(accion);
        this.agregarMouseListener(ml);
        topMenu.setMenuFunctions(this, ml, "Reportes");
    }
    
    private void agregarMouseListener(MouseListener ml) {
        goBackLbl.addMouseListener(ml);
    }

    private void agregarListener(ActionListener accion){
        listadoSolibtn.addActionListener(accion);
        listadoPrepBtn.addActionListener(accion);
        listadoRespBtn.addActionListener(accion);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topMenu = new vistas.swing.componentes.topMenu.topMenu();
        listadoSolibtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        goBackLbl = new javax.swing.JLabel();
        listadoPrepBtn = new javax.swing.JButton();
        listadoRespBtn = new javax.swing.JButton();
        backgroundImage1 = new vistas.swing.componentes.backgroundImage.backgroundImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(topMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, -1));

        listadoSolibtn.setText("Listado Solicitante");
        listadoSolibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoSolibtnActionPerformed(evt);
            }
        });
        getContentPane().add(listadoSolibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 160, 59));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO,");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 157, 31));

        goBackLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/swing/componentes/images/return.png"))); // NOI18N
        goBackLbl.setName("goBack"); // NOI18N
        getContentPane().add(goBackLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 44, -1, -1));

        listadoPrepBtn.setText("Listado Presupuestos");
        listadoPrepBtn.setToolTipText("");
        listadoPrepBtn.setInheritsPopupMenu(true);
        listadoPrepBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoPrepBtnActionPerformed(evt);
            }
        });
        getContentPane().add(listadoPrepBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 160, 59));

        listadoRespBtn.setLabel("Listado Responsable");
        listadoRespBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoRespBtnActionPerformed(evt);
            }
        });
        getContentPane().add(listadoRespBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 160, 59));
        getContentPane().add(backgroundImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listadoSolibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoSolibtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoSolibtnActionPerformed

    private void listadoPrepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoPrepBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoPrepBtnActionPerformed

    private void listadoRespBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoRespBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadoRespBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new VentanaHome().setVisible(true);
            }
        });
    }
     public JButton getSolicitantesList() {
        return listadoSolibtn;
    }

    public JButton getPresupuestosList() {
        return listadoPrepBtn;
    }
    
    public JButton getResponsableList() {
        return listadoRespBtn;
    }
    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vistas.swing.componentes.backgroundImage.backgroundImage backgroundImage1;
    private javax.swing.JLabel goBackLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listadoPrepBtn;
    private javax.swing.JButton listadoRespBtn;
    private javax.swing.JButton listadoSolibtn;
    private vistas.swing.componentes.topMenu.topMenu topMenu;
    // End of variables declaration//GEN-END:variables
}
